Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.define "dockerhost" do |dockerhost|
    dockerhost.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "ubuntu_dockerhost"
    end

    dockerhost.vm.network "forwarded_port", guest: 16543, host: 16543

    dockerhost.vm.provision "shell",
      inline: "apt-get update && apt-get install -y docker.io docker-compose"
    dockerhost.vm.provision "shell",
      inline: "docker-compose -f /vagrant/docker-compose.yml up -d"
  end
end
